# Generated by Django 4.1.6 on 2023-02-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('making_time', models.CharField(max_length=100)),
                ('serves', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=300)),
                ('cost', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recipes',
            },
        ),
        migrations.RunSQL(
            """INSERT INTO recipes (
            id,
            title,
            making_time,
            serves,
            ingredients,
            cost,
            created_at,
            updated_at
            )
            VALUES (
            1,
            'チキンカレー',
            '45分',
            '4人',
            '玉ねぎ,肉,スパイス',
            1000,
            '2016-01-10 12:10:12',
            '2016-01-10 12:10:12'
            );

            INSERT INTO recipes (
            id,
            title,
            making_time,
            serves,
            ingredients,
            cost,
            created_at,
            updated_at
            )
            VALUES (
            2,
            'オムライス',
            '30分',
            '2人',
            '玉ねぎ,卵,スパイス,醤油',
            700,
            '2016-01-11 13:10:12',
            '2016-01-11 13:10:12'
            ); """            
        ),
    ]
